version: '3'


services:
  admin-services:
    build: ../backend/admin-services/


  analytics-service:
    build: ../backend/analytics-service/


  audit-service:
    build: ../backend/audit-service/


  location-services:
    build: ../backend/location-services/



  notification-services:
    build: ../backend/notification-services/


  quality-services:
    build: ../backend/quality-services/


  task-services:
    build: ../backend/task-services/
    

  user-services:
    build: ../backend/user-services/